#!/usr/bin/python

import subprocess
import os
import signal
import sys


LOG_FILE="/var/log/yum_request_handler.log"
PID_FILE="/var/run/yum_request_handler.pid"

prog = ["python","-m","SimpleHTTPServer","9999"]
yum_proc = None

def _handle_sigterm( signal, frame ):
	yum_proc.kill()
	os._exit(0)

def _daemonize():
	parent_pid = os.getpid()
	pid = os.fork()
	if pid != 0:
		os._exit(0)
	os.chdir("/")
	os.setsid()
	pid = os.fork()
	if  pid != 0:
		os._exit(0)

if __name__ == "__main__":
	sys.stdout.close()
	_daemonize()
	logger = open(LOG_FILE,"w")
	pid_file = open( PID_FILE,"w")
	pid_file.write( str(os.getpid()) )
	pid_file.close()
	sys.stdout.close()
	signal.signal( signal.SIGTERM, _handle_sigterm )
	yum_proc = subprocess.Popen( prog, close_fds=True, stdout=subprocess.PIPE )
	while yum_proc.poll() is None:
		yum_proc.wait()
		#data = yum_proc.stdout.readline()
		#logger.write( data )








